;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-colon
	c-electric-delete-forward
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	smart-tab
	))

(setq mc/cmds-to-run-once
      '(
	elpy-nav-forward-indent
	elpy-nav-indent-shift-right
	switch-to-buffer
	))
